### ISSUE TITLE
node ./download-chromedrive.js issue

### ISSUE THREAD

**Issue by danielmapar** [electron/chromedriver#11]
Node: v6.8.0
NPM: 3.10.8

I am building an electron app in a windows 7 environment. However, when I do `npm install electron-chromedriver` (version 1.4.0) it outputs an error:

```
Error: Cannot find module `.src/init`
...
Failed at the electron-chromedriver@1.4.0 install script `node ./download-chromedriver.js`
```

Any ideas?

I already tried setting up some env variables with npm config:

`npm config set ELECTRON_MIRROR https://npm.taobao.org/mirrors/electron/`

but I get the same error.

**Comment by kevinsawicki** [comment]
Is there any more in the error stack trace?

**Comment by sgtaziz** [comment]
Been using electron for a while just fine, today I got on for my daily dose and I get that same error thrown in Travis-CI when issuing npm install.

```
Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/sgtaziz/RemoteMessages-Client/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by sgtaziz** [comment]
Not sure if related, but gulp sourcemaps is also having this issue as of ~6 hours ago. https://github.com/floridoo/gulp-sourcemaps/issues/238

**Comment by danielmapar** [comment]
![img_5387](https://cloud.githubusercontent.com/assets/4336805/19369157/2537ad66-917a-11e6-9eaa-e0250e63e426.JPG)
![Uploading IMG_5386.JPG…]()

**Comment by sgtaziz** [comment]
This has been fixed https://github.com/floridoo/gulp-sourcemaps/commit/93db5f5fd3a05c580b891c41771dc14c1ca585ea

**Comment by MarshallOfSound** [comment]
Just want to plug [`yarn`](yarnpkg.com) which would totally have stopped this issue from happened.  But kudos to the `gulp-sourcemaps` people who got this fixed ASAP
