### ISSUE TITLE
Cannot get automation extension

### ISSUE THREAD

**Issue by sean-hill** [electron/chromedriver#12]
Hey there,

I'm getting this issue while using electron chromedriver while following [this tutorial](https://github.com/electron/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md#3-connect-to-chrome-driver);

    unknown error: cannot get automation extensionfrom unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html

Any idea what this means?

**Comment by sean-hill** [comment]
It appears to be the `windowHandleSize()` webdriver.io command that causes it to throw this error.

**Comment by rbarros-daitan** [comment]
Any news on this issue? I´ve seen this when Maximize / Unmaximize / Set Window Position commands.

**Comment by codebytere** [comment]
This has been resolved on more recent version of Electron and by extension of ChromeDriver.
