### ISSUE TITLE
'node ./download-chromedriver.js' fails while installing MagicMirror² 

### ISSUE THREAD

**Issue by Projekt95** [electron/chromedriver#17]
[magic_mirror_debug.txt](https://github.com/electron/chromedriver/files/923713/magic_mirror_debug.txt)

I'm not sure why this happens.
NPM version: 4.5.0
Node Version: 6.10.2

Last lines after install fails, full debug.txt is attached:

```
electron-chromedriver@1.6.0 install /root/MagicMirror/node_modules/electron-chromedriver
node ./download-chromedriver.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/MagicMirror/node_modules/electron-chromedriver/download-chromedriver.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.6.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1

```

**Comment by andreicioromila** [comment]
I have the same issue on
node v6.9.5
npm v3.10.10

Please give us a hint on inspecting the problem

**Comment by Projekt95** [comment]
@andreicioromila we found a solution for this a while ago :)
check it out here; https://github.com/MichMich/MagicMirror/issues/857

**Comment by roramirez** [comment]
Hi @Projekt95 , so ... you need close this issue.

Thanks!
