### ISSUE TITLE
error on npm install on OSX

### ISSUE THREAD

**Issue by syonip** [electron/chromedriver#19]
Hi,
Getting following error :

`
npm install --save-dev electron-chromedriver npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-zapTJKvK4eACcTgBVlyeFaJ63cXujpWjOLKKRHL8uYOHLp5CYHYgXlM6kN8L7zjz5uVjA51hy9NsSyIQZ8S3Mw== integrity checksum failed when using sha512: wanted sha512-zapTJKvK4eACcTgBVlyeFaJ63cXujpWjOLKKRHL8uYOHLp5CYHYgXlM6kN8L7zjz5uVjA51hy9NsSyIQZ8S3Mw== but got sha1-WmNWbkpGhUE4Yerwh9yqmg42KgM=. (18302 bytes) > electron-chromedriver@1.7.1 install /Users/johnny/git/vanilla/node_modules/electron-chromedriver > node ./download-chromedriver.js module.js:487 throw err; ^ Error: Cannot find module 'process-nextick-args' at Function.Module._resolveFilename (module.js:485:15)at Function.Module._load (module.js:437:25) at Module.require (module.js:513:17) at require (internal/module.js:11:18) at Object.<anonymous> (/Users/johnny/git/vanilla/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_readable.js:6:23) at Module._compile (module.js:569:30) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:503:32) at tryModuleLoad (module.js:466:12) at Function.Module._load (module.js:458:3) npm WARN zone@0.1.4 No license field. npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.0.2 (node_modules/7zip-bin-win): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"}) npmERR!code ELIFECYCLE npmERR!errno 1 npmERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js` npmERR! Exit status 1 npmERR!npmERR! Failed at the electron-chromedriver@1.7.1 install script. npmERR! This is probably not a problem with npm. There is likely additional logging output above. npmERR! A complete log of this run can be found in: npmERR!/Users/johnny/.npm/_logs/2017-07-01T10_42_37_269Z-debug.log
`

Trying to manually install the missing 'process-nextick-args' throws more missing module errors, and so on.

Thanks.

**Comment by syonip** [comment]
node version 8.1.3
npm version 5.0.3

**Comment by jkleinsc** [comment]
@syonip can you retry this? I just tried it on OSX with node 8.1.3/npm 5.0.3 and it works correctly.

1.8.0 was just released, so if you are working with 1.7.x, you'll need to specify the 1.7.1 version, eg:
```sh
npm install electron-chromedriver@1.7.1
```

**Comment by jkleinsc** [comment]
Closing due to lack of response.
