### ISSUE TITLE
Error install on Windows

### ISSUE THREAD

**Issue by Ribeiro** [electron/chromedriver#20]
Here's the npm-debug.log part:

87428 info lifecycle electron-chromedriver@1.7.1~install: electron-chromedriver@1.7.1
87429 verbose lifecycle electron-chromedriver@1.7.1~install: unsafe-perm in lifecycle true
87430 verbose lifecycle electron-chromedriver@1.7.1~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\electron-chromedriver\node_modules\.bin;D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\.bin;D:\Users\008188L1\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;D:\Users\008188L1\bin;C:\oracle\ora92\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\DMIX;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\dotnet;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;D:\Users\008188L1\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
87431 verbose lifecycle electron-chromedriver@1.7.1~install: CWD: D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\electron-chromedriver
87432 silly lifecycle electron-chromedriver@1.7.1~install: Args: [ '/d /s /c', 'node ./download-chromedriver.js' ]
87433 silly lifecycle electron-chromedriver@1.7.1~install: Returned: code: 1  signal: null
87434 info lifecycle electron-chromedriver@1.7.1~install: Failed to exec install script
87435 verbose unlock done using D:\Users\008188L1\AppData\Roaming\npm-cache\_locks\staging-c221d9790d1cd1b7.lock for D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\.staging
87436 silly rollbackFailedOptional Starting
87437 silly rollbackFailedOptional Finishing
87438 silly runTopLevelLifecycles Finishing
87439 silly install printInstalled
87440 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
87441 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
87442 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
87442 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
87442 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
87442 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
87443 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
87444 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
87445 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
87445 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
87445 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
87445 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
87446 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.1.0 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
87447 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.1.0: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
87448 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    linux
87448 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
87448 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
87448 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
87449 warn ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
87450 verbose If you need help, you may report this error at:
87450 verbose     <https://github.com/npm/npm/issues>
87451 warn integrador@1.6.86 No repository field.
87452 verbose If you need help, you may report this error at:
87452 verbose     <https://github.com/npm/npm/issues>
87453 warn integrador@1.6.86 No license field.
87454 verbose If you need help, you may report this error at:
87454 verbose     <https://github.com/npm/npm/issues>
87455 verbose stack Error: electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
87455 verbose stack Exit status 1
87455 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
87455 verbose stack     at emitTwo (events.js:106:13)
87455 verbose stack     at EventEmitter.emit (events.js:191:7)
87455 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
87455 verbose stack     at emitTwo (events.js:106:13)
87455 verbose stack     at ChildProcess.emit (events.js:191:7)
87455 verbose stack     at maybeClose (internal/child_process.js:891:16)
87455 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
87456 verbose pkgid electron-chromedriver@1.7.1
87457 verbose cwd D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe
87458 error Windows_NT 6.1.7601
87459 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
87460 error node v6.11.1
87461 error npm  v3.10.10
87462 error code ELIFECYCLE
87463 error electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
87463 error Exit status 1
87464 error Failed at the electron-chromedriver@1.7.1 install script 'node ./download-chromedriver.js'.
87464 error Make sure you have the latest version of node.js and npm installed.
87464 error If you do, this is most likely a problem with the electron-chromedriver package,
87464 error not with npm itself.
87464 error Tell the author that this fails on your system:
87464 error     node ./download-chromedriver.js
87464 error You can get information on how to open an issue for this project with:
87464 error     npm bugs electron-chromedriver
87464 error Or if that isn't available, you can get their info via:
87464 error     npm owner ls electron-chromedriver
87464 error There is likely additional logging output above.
87465 verbose exit [ 1, true ]

Can someone help me out with this? Thanks in advance!  =)

**Comment by jkleinsc** [comment]
@Ribeiro can you retry this?  I just tried it on Windows and it works correctly.  

1.8.0 was just released, so if you are working with 1.7.x, you'll need to specify the 1.7.1 version, eg: 
`npm install electron-chromedriver@1.7.1`

**Comment by mceachen** [comment]
I had a similar issue with the download failing--my prior-fetched zipfile didn't match the checksum. Removing my `~/AppData/Local/electron` directory [solved the issue](https://github.com/electron/spectron/issues/265) for me.

**Comment by jkleinsc** [comment]
Closing due to lack of response.
