### ISSUE TITLE
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0 when run chromedriver from terminal 

### ISSUE THREAD

**Issue by wangjiangchuan** [electron/chromedriver#21]
I use the command you provide in the readme.md and install the spectron all using nom.
When I use the terminal to run chromedrive, it provides the following msg:

imac:Desktop denny$ chromedriver
Starting ChromeDriver (v2.6.232908) on port 9515
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0  

Those commands used to install chromedriver and spectron are the followings:
npm install --save-dev electron-chromedriver  
npm install --save-dev spectron  

My operation system is Mac OS Sierra. 

Actually, I have tried to solve this problems through almost any methods I searched, but failed, please tell me.

**Comment by codebytere** [comment]
This has been resolved on later releases of Electron and by extension of ChromeDriver.
