### ISSUE TITLE
Cannot install 1.8.0 on Linux

### ISSUE THREAD

**Issue by DarrenCook** [electron/chromedriver#25]
npm install electron-chromedriver@1.8.0 always fails with:

> Error: Generated checksum for "chromedriver-v1.8.0-linux-x64.zip" did not match expected checksum.

Q. Is there a way to be told the two checksums, so I can try and find out which one is correct?

Inspired by https://github.com/electron/spectron/issues/265 I have been deleting node_modules of my project, and I also deleted ~/.npm/. But neither helped.

I also tried as root, doing a global install:

     sudo npm install -g electron-chromedriver@1.8.0

It fails with:

> Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron-chromedriver/.electron'

This seems like a simple bug, as /usr/lib/node_modules/ currently only contains an "npm" directory. I.e. mkdir needs to be set to make parent directories as needed. (`mkdir -p` if it is using the bash command.)

**Comment by kazuar** [comment]
I have the same error on OSX 

```
Error: Generated checksum for "chromedriver-v1.8.0-darwin-x64.zip" did not match expected checksum.
```

Did you manage to find a solution for this issue?

**Comment by jkleinsc** [comment]
This should now be corrected.  One thing you may need to do is to clear out the `.electron` directory in your home directory.

**Comment by danielecr** [comment]
I still have the same exact Error message. Something is changed back again?
```
Error: Generated checksum for "chromedriver-v1.8.0-linux-x64.zip" did not match expected checksum.
```

**Comment by kazuar** [comment]
If you're still getting this error, try to clear this directory as well:

```
~/Library/Caches/electron
```
