### ISSUE TITLE
Automatic release of electron-chromedriver when new Electron release is published

### ISSUE THREAD

**Issue by remss** [electron/chromedriver#30]
Currently electron-chromedriver is still in 3.0.0-beta.1 even if Electron 3.0.0 has been released.
I believe that it's because bump is a manual process that takes time to do it.
Can we imagine a script that bump version to package.json and publish electron-chromedriver when a new electron release is published ?

**Comment by jinwyp** [comment]
now electron is 4.0.5 .

**Comment by CapOM** [comment]
+1, latest tag of electron-chromedriver is beta 4.0
