### ISSUE TITLE
Update electron-chromedriver to use Chromedriver v2.38 for Electron 3

### ISSUE THREAD

**Issue by happypoulp** [electron/chromedriver#32]
Hi,

I had some issues using Spectron with **Electron 3** and from what I found those issue are related to the chromedriver version that is used in electron-chromedriver. All the issues were related to **"unknown session ID"** and **"cannot determine loading status"**.

I **tried using electron-chromedriver ^3.0.0-beta.1** but my issues were still present.

I saw here http://chromedriver.chromium.org/downloads that **Chromedriver v2.38** is supposed to contain fixes for the 2 issues above (see changelog for Chromedriver v2.38) and indeed, it worked perfectly, no more **"unknown session ID"** and **"cannot determine loading status"** errors.

Can you update to use Chromedriver v2.38 please?

Thanks!

**Comment by fansanelli** [comment]
Hi. I think is not possible to update to 2.38, also setting latest Electron version (3.1.3) Chromedriver 2.36 will be downloaded...
Cheers,
Francesco
