### ISSUE TITLE
Version override not implemented?

### ISSUE THREAD

**Issue by sameoldmadness** [electron/chromedriver#67]
Documentation states that:

> The version downloaded can be overriden by setting the ELECTRON_CUSTOM_VERSION environment variable.

Although I cannot find a place where this variable is used in the code.

I've tried to specify the version, but it does not change anything.

```
ELECTRON_CUSTOM_VERSION=10.0.0-beta.17 yarn install
```

Is this feature not implemented or am I missing something?

**Comment by codebytere** [comment]
This does work - you need to be on Chromedriver v12 minimum. It works via https://github.com/electron/get#overriding-the-version-downloaded, which is what Chromedriver uses to perform the download.
