### ISSUE TITLE
Specify ELECTRON_MIRROR to a directory/or file on disk

### ISSUE THREAD

**Issue by CMCDragonkai** [electron/chromedriver#78]
Our build system is reproducible so it does not allow any network access. Is there a way to specify that the installation should just a prespecified file that's on disk or a directory? Similar to the `electronZipDir` used by `@electron-forge/cli`?

**Comment by milahu** [comment]
maybe populate `~/.cache/electron/` as described in https://github.com/electron/get#how-it-works

**Comment by codebytere** [comment]
Closing in agreement with above.
